### ISSUE TITLE
instant.io broken in firefox nightly

### ISSUE THREAD

**Issue by beingalink** [feross/instant.io#22]
I get following in the console:
TypeError: asm.js type error: expecting argument type declaration for 'e' of the form 'arg = arg|0' or 'arg = +arg' or 'arg = fround(arg)'

Then when it tries to hash a file:
AssertionError: false == true

I guess it might be related to this: https://github.com/subrosa-io/subrosa-client/issues/39

**Comment by feross** [comment]
The asm error appears to only be a warning. I opened an issue on Rusha (https://github.com/srijs/rusha/issues/27). The site still works for me, and I can send/receive files from Firefox. I'm seeing an error when trying to receive a file in Firefox (NS_ERROR_UNEXPECTED). Is that what you see?

What file are you attempting to hash? How big is it?

**Comment by beingalink** [comment]
I try to create a torrent by giving the app a file to hash via the browse button. It shows "Creating .torrent file..." but nothing happens afterwards. With current nightly build I get: "Error: Invalid torrent identifier" in bundle.js or "AssertionError: false == true".

**Comment by feross** [comment]
Fixed the asm.js warning, see: https://github.com/feross/webtorrent/issues/281

Still unsure about the other error.

**Comment by beingalink** [comment]
Yes, the asm warning is fixed indeed: Console says "Successfully compiled asm.js code (total compilation time 5ms; not stored in cache (too small to benefit))".
But creating a torrent still doesn't work. I still get "AssertionError: false == true" in <unknown>. Perhaps it's a firefox issue in the end.

**Comment by feross** [comment]
I released new versions of `webtorrent-tracker` and `webtorrent-swarm` to fix this issue. Please try https://instant.io one more time and confirm that it's working now.

**Comment by feross** [comment]
If it's not working, please leave a comment and I'll re-open.

**Comment by beingalink** [comment]
Unfortunately this doesn't seem to have fixed the issue. Creating a torrent hangs somewhere in the process and I still get the "AssertionError: false == true" message.

**Comment by feross** [comment]
How large is the file you're using?

**Comment by beingalink** [comment]
I tried files starting from a few KBs to a few (<5) MBs.

**Comment by feross** [comment]
Can you email me the files you're using? feross@feross.org. I can't seem
reproduce the issue on my end.

**Comment by beingalink** [comment]
I just sent you 2 small test files but I doubt it's about the files I used. If it works for you with current firefox nightly build, I guess it might be an issue with the mac version (I'm on a macbook) or some setting I use.

**Comment by beingalink** [comment]
I just tested on FirefoxDeveloperEdition from 03-18 and it works fine there. I guess it's something about the nightly firefox builds having new stuff enabled that prevents instant.io from working or me having done something stupid with my install.

**Comment by feross** [comment]
Oh, you should disable "Electrolysis" in Firefox Nightly since it breaks
all kinds of things.
https://wiki.mozilla.org/Electrolysis#Enabling_and_Disabling_Electrolysis
See if that fixes the issue in Nightly for you.

**Comment by beingalink** [comment]
I already tried with and without e10s enabled. That doesn't seem to make any difference. I even cleared the cache and shift reloaded several times but this doesn't help.

**Comment by beingalink** [comment]
I just checked the console with e10s disabled. There's a different error message now: "Error: Invalid torrent identifier" in "bundle.js:4:334". Perhaps that helps you to identify the issue.

**Comment by feross** [comment]
Looks like Fx Nightly broke something, my guess is that they broke the `crypto.subtle` api which does sha1 hashing when on `https:` origins. It works in all other versions of Fx.

**Comment by beingalink** [comment]
I filed a bug on bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1145058

**Comment by beingalink** [comment]
Seems like the bug has been fixed.

**Comment by feross** [comment]
Yep – thanks for finding and filing the issue!
